IBN-2419 make hue bridge read non blocking
AlJungOrg/smarthome pull request #52
Opened 2019-06-11 11:10 UTC by Maw-Jung

The call for the current hue bridge configuration was blocking and
didn't return prior to a timeout, which made the ui freeze. By
triggering a job to do just that, the ui keeps being responsive.

2019-06-11 11:31 UTC, t-esch requested changes
Should this included in 1.2.1650 or 1.2.1700?

2019-06-11 11:31 UTC, t-esch commented on extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java
> +        scheduler.schedule(command, DISCOVERY_SCAN_DELAY, SECONDS);
Shouldn't this be `scheduler.execute(() => { ... } );`

2019-06-11 11:31 UTC, t-esch commented on extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/internal/discovery/HueLightDiscoveryService.java
> +    private ScheduledExecutorService scheduler;
The SonosDiscoveryService uses
`
private final ExecutorService pool = ThreadPoolManager.getPool(getClass().getSimpleName());
pool.submit(() -> { ... }
`

2019-07-10 07:26 UTC, pwolfart commented
I don`t think this is critical so lets place this in 1.2.1700.

2019-07-30 13:13 UTC, merged